name: sshuttle
version: 1.1.1
summary: where transparent proxy meets VPN meets ssh
description: |
  As far as I know, sshuttle is the only program that solves the following
  common case:

  - Your client machine (or router) is Linux, FreeBSD, or MacOS.

  - You have access to a remote network via ssh.

  - You don't necessarily have admin access on the remote network.

  - The remote network has no VPN, or only stupid/complex VPN
    protocols (IPsec, PPTP, etc). Or maybe you *are* the
    admin and you just got frustrated with the awful state of
    VPN tools.

  - You don't want to create an ssh port forward for every
    single host/port on the remote network.

  - You hate openssh's port forwarding because it's randomly
    slow and/or stupid.

  - You can't use openssh's PermitTunnel feature because
    it's disabled by default on openssh servers; plus it does
    TCP-over-TCP, which has `terrible performance`_.

base: core22
grade: stable
confinement: strict

parts:
  sshuttle:
    plugin: python
    source: https://github.com/sshuttle/sshuttle.git
    source-tag: "v1.1.1"
    override-pull: |
      snapcraftctl pull
      patch -p1 -i $CRAFT_PROJECT_DIR/netstat_snap.patch
    build-packages:
      - git
      - python3
      - snapcraft
    stage-packages:
      - net-tools

apps:
  sshuttle:
    command: bin/sshuttle
    environment:
      PATH: ${SNAP}/bin:${PATH}
    plugs:
      - home
